#!/bin/bash
# ww3_seq_run  version 1.03

  #********************************************************************#
  #                                                                    #
  # Program to run sequential simulation with WW3.                     #
  # In this version a run should be already in execution.              #
  #                                                                    #
  # USE:                                                               #
  # - select the start and end date. Run should be divided monthly     #
  #                                                                    #
  #                                              Author: Dario Pelli   #
  # Last update: 11-Feb-2016                                           #
  #                                                                    #
  #********************************************************************#
  
  # Write the command that you want to use for WW3 running
  command="ww3_shel_OMP"

  echo -n "Write the last date (yyyy mm):"
  read lyear lmonth

  echo -n "Write the end date (yyyy mm):"
  read eyear emonth

  main_dir=$HOME/WEA_WW3/   # work directory
  LIMIT=100                 # number of waiting
  STEP=600                  # time of waiting

  # Start of the calendar LOOP

  for ((year=lyear; year <= eyear; year++))  # year counter
  do

    for month in $(seq -f "%02g" 01 12)      # month counter 
    do

      # Define the number of days for each month
       case $month in
         04|06|09|11)  end_day=30 
         ;;
         02)
            # Define the bissextile year
            if [ $(expr $year % 4 ) -eq 0  ]  
            then
              if [ $(expr $year % 100) -eq 0 ] && [ $($year % 400) -ne 0 ]
              then
                end_day=28
              else
                end_day=29
              fi
            else
              end_day=28
            fi
         ;;
         *)  end_day=31 
         ;;
       esac
  
      # start if the date is equal to the initial date        
      if [ $year -eq $lyear ] && [ $month -ge $lmonth ] || [ $year -gt $lyear ]   
      then 

        # Define the old and the new simulation
        sim_old=${year}${month}
        newyear=$year
        let "newmonth = $((10#$month + 1))"

        if [ $month -eq 12 ]
        then
          let "newyear = $(($year + 1))"
        fi

        if [ ${newmonth} -eq 13 ]
        then
          newmonth=1
        fi

        newmonth=$(printf "%02g" $newmonth)
        sim_new=${newyear}${newmonth}

        # Waiting for the end of the previous run

        for ((a=1; a <= LIMIT; a++))
        do
          if [ -e ${main_dir}${sim_old}/restart0${end_day}.ww3 ]
          then
            echo "$sim_old $sim_new $end_day"
            ln -s ${main_dir}${sim_old}/restart0${end_day}.ww3 ${main_dir}${sim_new}/restart.ww3
            cd ${main_dir}${sim_new}
            ${main_dir}exe/${command} | tee ${command}.out
            break
          fi
          sleep $STEP
        done
      fi   
      
      # break the loop if the ending year and month are reached
      if [ "$year" -eq "$eyear" ] && [ "$month" -eq "$emonth" ]
      then
        break
      fi   

    done
  
  done
  
  # End of the calendar LOOP

  exit
